<?php

use Illuminate\Database\Seeder;

class CityTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('city')->delete();
        
        \DB::table('city')->insert(array (
            0 => 
            array (
                'city_id' => 1,
                'city_code' => 'SG',
                'city_name' => 'Hồ Chí Minh',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 1,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'city_id' => 2,
                'city_code' => 'HN',
                'city_name' => 'Hà Nội',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 2,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'city_id' => 3,
                'city_code' => 'BD',
                'city_name' => 'Bình Dương',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 3,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'city_id' => 4,
                'city_code' => 'DDN',
                'city_name' => 'Đà Nẵng',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 4,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'city_id' => 5,
                'city_code' => 'HP',
                'city_name' => 'Hải Phòng',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 5,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'city_id' => 6,
                'city_code' => 'LA',
                'city_name' => 'Long An',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 6,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'city_id' => 7,
                'city_code' => 'VT',
                'city_name' => 'Bà Rịa Vũng Tàu',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 7,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'city_id' => 8,
                'city_code' => 'AG',
                'city_name' => 'An Giang',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 8,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'city_id' => 9,
                'city_code' => 'BG',
                'city_name' => 'Bắc Giang',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 9,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'city_id' => 10,
                'city_code' => 'BK',
                'city_name' => 'Bắc Kạn',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 10,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'city_id' => 11,
                'city_code' => 'BL',
                'city_name' => 'Bạc Liêu',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 11,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'city_id' => 12,
                'city_code' => 'BN',
                'city_name' => 'Bắc Ninh',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 12,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'city_id' => 13,
                'city_code' => 'BTR',
                'city_name' => 'Bến Tre',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 13,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'city_id' => 14,
                'city_code' => 'BDD',
                'city_name' => 'Bình Định',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 14,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'city_id' => 15,
                'city_code' => 'BP',
                'city_name' => 'Bình Phước',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 15,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'city_id' => 16,
                'city_code' => 'BTH',
                'city_name' => 'Bình Thuận  ',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 16,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'city_id' => 17,
                'city_code' => 'CM',
                'city_name' => 'Cà Mau',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 17,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'city_id' => 18,
                'city_code' => 'CN',
                'city_name' => 'Cả Nước',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 18,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'city_id' => 19,
                'city_code' => 'CT',
                'city_name' => 'Cần Thơ',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 19,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'city_id' => 20,
                'city_code' => 'CB',
                'city_name' => 'Cao Bằng',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 20,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'city_id' => 21,
                'city_code' => 'DDL',
                'city_name' => 'Đắk Lắk',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 21,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'city_id' => 22,
                'city_code' => 'DNO',
                'city_name' => 'Đắk Nông',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 22,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'city_id' => 23,
                'city_code' => 'DDB',
                'city_name' => 'Điện Biên',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 23,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'city_id' => 24,
                'city_code' => 'DNA',
                'city_name' => 'Đồng Nai',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 24,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'city_id' => 25,
                'city_code' => 'DDT',
                'city_name' => 'Đồng Tháp',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 25,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'city_id' => 26,
                'city_code' => 'GL',
                'city_name' => 'Gia Lai',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 26,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'city_id' => 27,
                'city_code' => 'HG',
                'city_name' => 'Hà Giang',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 27,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'city_id' => 28,
                'city_code' => 'HNA',
                'city_name' => 'Hà Nam',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 28,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'city_id' => 29,
                'city_code' => 'HT',
                'city_name' => 'Hà Tĩnh',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 29,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'city_id' => 30,
                'city_code' => 'HD',
                'city_name' => 'Hải Dương',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 30,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'city_id' => 31,
                'city_code' => 'HGI',
                'city_name' => 'Hậu Giang',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 31,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'city_id' => 32,
                'city_code' => 'HB',
                'city_name' => 'Hòa Bình',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 32,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'city_id' => 33,
                'city_code' => 'HY',
                'city_name' => 'Hưng Yên',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 33,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'city_id' => 34,
                'city_code' => 'KH',
                'city_name' => 'Khánh Hòa',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 34,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'city_id' => 35,
                'city_code' => 'KG',
                'city_name' => 'Kiên Giang',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 35,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'city_id' => 36,
                'city_code' => 'KT',
                'city_name' => 'Kon Tum',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 36,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'city_id' => 37,
                'city_code' => 'LCH',
                'city_name' => 'Lai Châu',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 37,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'city_id' => 38,
                'city_code' => 'LDD',
                'city_name' => 'Lâm Đồng',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 38,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'city_id' => 39,
                'city_code' => 'LS',
                'city_name' => 'Lạng Sơn',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 39,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'city_id' => 40,
                'city_code' => 'LCA',
                'city_name' => 'Lào Cai',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 40,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'city_id' => 41,
                'city_code' => 'NDD',
                'city_name' => 'Nam Định',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 41,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'city_id' => 42,
                'city_code' => 'NA',
                'city_name' => 'Nghệ An',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 42,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'city_id' => 43,
                'city_code' => 'NB',
                'city_name' => 'Ninh Bình',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 43,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'city_id' => 44,
                'city_code' => 'NT',
                'city_name' => 'Ninh Thuận',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 44,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'city_id' => 45,
                'city_code' => 'PT',
                'city_name' => 'Phú Thọ',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 45,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'city_id' => 46,
                'city_code' => 'PY',
                'city_name' => 'Phú Yên',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 46,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'city_id' => 47,
                'city_code' => 'QB',
                'city_name' => 'Quảng Bình',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 47,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'city_id' => 48,
                'city_code' => 'QNA',
                'city_name' => 'Quảng Nam',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 48,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'city_id' => 49,
                'city_code' => 'QNG',
                'city_name' => 'Quảng Ngãi',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 49,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'city_id' => 50,
                'city_code' => 'QNI',
                'city_name' => 'Quảng Ninh',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 50,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'city_id' => 51,
                'city_code' => 'QT',
                'city_name' => 'Quảng Trị',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 51,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'city_id' => 52,
                'city_code' => 'ST',
                'city_name' => 'Sóc Trăng',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 52,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'city_id' => 53,
                'city_code' => 'SL',
                'city_name' => 'Sơn La',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 53,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            53 => 
            array (
                'city_id' => 54,
                'city_code' => 'TNI',
                'city_name' => 'Tây Ninh',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 54,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            54 => 
            array (
                'city_id' => 55,
                'city_code' => 'TB',
                'city_name' => 'Thái Bình',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 55,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            55 => 
            array (
                'city_id' => 56,
                'city_code' => 'TN',
                'city_name' => 'Thái Nguyên',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 56,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            56 => 
            array (
                'city_id' => 57,
                'city_code' => 'TH',
                'city_name' => 'Thanh Hóa',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 57,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            57 => 
            array (
                'city_id' => 58,
                'city_code' => 'TTH',
                'city_name' => 'Thừa Thiên Huế',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 58,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            58 => 
            array (
                'city_id' => 59,
                'city_code' => 'TG',
                'city_name' => 'Tiền Giang',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 59,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            59 => 
            array (
                'city_id' => 60,
                'city_code' => 'TV',
                'city_name' => 'Trà Vinh',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 60,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            60 => 
            array (
                'city_id' => 61,
                'city_code' => 'TQ',
                'city_name' => 'Tuyên Quang',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 61,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            61 => 
            array (
                'city_id' => 62,
                'city_code' => 'VL',
                'city_name' => 'Vĩnh Long',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 62,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            62 => 
            array (
                'city_id' => 63,
                'city_code' => 'VP',
                'city_name' => 'Vĩnh Phúc',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 63,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            63 => 
            array (
                'city_id' => 64,
                'city_code' => 'YB',
                'city_name' => 'Yên Bái',
                'city_alias' => '',
                'city_country' => 245,
                'city_order' => 64,
                'city_status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}